### ISSUE TITLE
build problem on Mac OS X

### ISSUE THREAD

**Issue by Selur** [HomeOfVapourSynthEvolution/VapourSynth-IT#5]
trying to build the filter on Mac OS X (Xcode, home-brew and vapoursynth are installed) I get:

> Selurs-Mac-mini:vsfilters selur$ cd VapourSynth-IT/
> Selurs-Mac-mini:VapourSynth-IT selur$ ls
> GNUmakefile LICENSE     README.md   configure   msvc        src
> Selurs-Mac-mini:VapourSynth-IT selur$ ./configure 
> CXXFLAGS/LDFLAGS checking...
> checking for vapoursynth headers...
> 
> settings...
> CXX          = g++
> LD           = g++
> STRIP        = strip
> CXXFLAGS     = -O2 -ffast-math -std=c++11 -Wall -I. -I./src  -D__SSE -mssse3 -I/usr/local/Cellar/vapoursynth/33.1/include/vapoursynth -I/usr/local/Cellar/zimg/2.2.1/include
> LDFLAGS      = -shared -Wl,-Bsymbolic -dynamiclib -Wl,-undefined,suppress -Wl,-read_only_relocs,suppress -Wl,-flat_namespace  
> LIBS         =  
> LIBNAME      = libit.dylib
> install path = /usr/local/lib/vapoursynth
> configure finished.
> Selurs-Mac-mini:VapourSynth-IT selur$ make
> g++ -O2 -ffast-math -std=c++11 -Wall -I. -I./src  -D__SSE -mssse3 -I/usr/local/Cellar/vapoursynth/33.1/include/vapoursynth -I/usr/local/Cellar/zimg/2.2.1/include -c src/vs_it_c.cpp -o src/vs_it_c.o
> g++ -O2 -ffast-math -std=c++11 -Wall -I. -I./src  -D__SSE -mssse3 -I/usr/local/Cellar/vapoursynth/33.1/include/vapoursynth -I/usr/local/Cellar/zimg/2.2.1/include -c src/vs_it.cpp -o src/vs_it.o
> src/vs_it.cpp:79:47: error: use of undeclared identifier 'aligned_alloc'; did you mean 'vs_aligned_malloc'?
>         env->m_edgeMap = static_cast<unsigned char*>(_aligned_malloc(size, 16));
>                                                      ^
> ./src/vs_it_interface.h:37:42: note: expanded from macro '_aligned_malloc'
> # define _aligned_malloc(decl, alignment) aligned_alloc(alignment, decl)
> 
> ```
>                                      ^
> ```
> 
> /usr/local/Cellar/vapoursynth/33.1/include/vapoursynth/VSHelper.h:56:18: note: 'vs_aligned_malloc' declared here
> static inline T\* vs_aligned_malloc(size_t size, size_t alignment) {
>                  ^
> src/vs_it.cpp:82:52: error: use of undeclared identifier 'aligned_alloc'; did you mean 'vs_aligned_malloc'?
>         env->m_motionMap4DI = static_cast<unsigned char*>(_aligned_malloc(size, 16));
>                                                           ^
> ./src/vs_it_interface.h:37:42: note: expanded from macro '_aligned_malloc'
> # define _aligned_malloc(decl, alignment) aligned_alloc(alignment, decl)
> 
> ```
>                                      ^
> ```
> 
> /usr/local/Cellar/vapoursynth/33.1/include/vapoursynth/VSHelper.h:56:18: note: 'vs_aligned_malloc' declared here
> static inline T\* vs_aligned_malloc(size_t size, size_t alignment) {
>                  ^
> src/vs_it.cpp:85:55: error: use of undeclared identifier 'aligned_alloc'; did you mean 'vs_aligned_malloc'?
>         env->m_motionMap4DIMax = static_cast<unsigned char*>(_aligned_malloc(size, 16));
>                                                              ^
> ./src/vs_it_interface.h:37:42: note: expanded from macro '_aligned_malloc'
> # define _aligned_malloc(decl, alignment) aligned_alloc(alignment, decl)
> 
> ```
>                                      ^
> ```
> 
> /usr/local/Cellar/vapoursynth/33.1/include/vapoursynth/VSHelper.h:56:18: note: 'vs_aligned_malloc' declared here
> static inline T\* vs_aligned_malloc(size_t size, size_t alignment) {
>                  ^
> 3 errors generated.
> make: **\* [src/vs_it.o] Error 1

Do I need to install any additional tools to build this?

**Comment by msg7086** [comment]
Please be advised that currently I'm not actively maintaining this project. Time passes quickly and some code may not be compatible with latest version of VapourSynth or different compilers. If you managed to fix the errors, a pull request is welcomed.
